"""
Django settings for force_displaying_website project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured


def get_env_var_value(env_variable):
    try:
      	return os.environ[env_variable]
    except KeyError:
        error_msg = f'Set the "{env_variable}" environment variable'
        raise ImproperlyConfigured(error_msg)


# Build paths inside the project like this: pathlib.Path(BASE_DIR/'sub_path')
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# New key can be generated by using Django:
#   from django.core.management.utils import get_random_secret_key  
#   print(get_random_secret_key())
SECRET_KEY = get_env_var_value('FORCE_DISPLAYING_WEBSITE_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if get_env_var_value('FORCE_DISPLAYING_WEBSITE_DEBUG') == 'True' else False

ALLOWED_HOSTS = ['daphne']


# Application definition

INSTALLED_APPS = [
    # Default apps ================
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Default apps ================

    # Django Channels
    'channels',

    # Django Crispy Forms
    'crispy_forms',

    # Custom apps
    'force_app.apps.ForceAppConfig',
    'users.apps.UsersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'force_displaying_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "force_displaying_website.routing.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_var_value('FORCE_DISPLAYING_WEBSITE_DATABASE_NAME'),
        'USER': get_env_var_value('FORCE_DISPLAYING_WEBSITE_DATABASE_USER_NAME'),
        'PASSWORD': get_env_var_value('FORCE_DISPLAYING_WEBSITE_DATABASE_PASSWORD'),
        'HOST': get_env_var_value('FORCE_DISPLAYING_WEBSITE_DATABASE_HOST'),
        'PORT': get_env_var_value('FORCE_DISPLAYING_WEBSITE_DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR/'static'


# Model which is used for authentication
AUTH_USER_MODEL = 'users.EmailUser'


# Set django-crispy-forms to use bootstrap 4 templates
CRISPY_TEMPLATE_PACK = 'bootstrap4'


LOGIN_URL = 'users-login'               # URL address for login page
LOGIN_REDIRECT_URL = 'force_app-home'   # URL address where to redirect after login
LOGOUT_REDIRECT_URL = 'users-login'     # URL address where to redirect after logout

# Django Channels layer configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
